DROP TABLE testdb.tbl4alter_new;
DROP TABLE testdb.test_msck;
DROP TABLE testdb.teacher;
DROP TABLE testdb.tbl4drop_no_r;
DROP TABLE testdb.view4drop_no_r;
DROP TABLE testdb.employees02;
DROP TABLE testdb.staged_employees02;
DROP TABLE testdb.staged_employees022;
DROP TABLE testdb.tbl4alter_new;
DROP DATABASE unaccessdb;
DROP DATABASE testdb CASCADE;
DROP DATABASE db4drop_cascade CASCADE;
