DROP TABLE testdb.supply;
DROP TABLE testdb.whoyouare;
DROP TABLE testdb.log_messages;
DROP TABLE testdb.log_messages_external;
DROP TABLE testdb.log_messages2;
DROP TABLE testdb.test_enable_disable;
DROP TABLE testdb.test_partition_serde;
DROP TABLE testdb.test_serde;
DROP TABLE testdb.session_test;
DROP TABLE testdb.sessionization_step_one_origins;
DROP TABLE testdb.employees02;
DROP TABLE testdb.src_employees02;
DROP TABLE testdb.table001;
DROP TABLE testdb.table002;
DROP TABLE testdb.src_employees;
DROP TABLE testdb.employees;
DROP TABLE testdb.partition_table001;
DROP TABLE testdb.partition_table002;
DROP TABLE testdb.collecttest;
DROP TABLE testdb.test_msck;
DROP TABLE testdb.employees_props;

DROP TABLE testdb.tbl4alter_new;
DROP TABLE testdb.test_msck;
DROP TABLE testdb.teacher;
DROP TABLE testdb.tbl4drop_no_r;
DROP TABLE testdb.view4drop_no_r;

DROP TABLE testdb.tbl4alter_new;
DROP DATABASE unaccessdb;
DROP DATABASE testdb CASCADE;
DROP DATABASE db4drop_cascade CASCADE;
