DROP DATABASE IF EXISTS test_db CASCADE;
CREATE DATABASE test_db WITH DBPROPERTIES ('creator' = 'hadoop-QA', 'date' = '2017-10-02');
SHOW DATABASES LIKE 'test_db';
DROP DATABASE test_db;
SHOW DATABASES LIKE 'test_db';