DROP DATABASE IF EXISTS test_db2 CASCADE;
CREATE DATABASE test_db2 WITH DBPROPERTIES ('creator' = 'hadoop-QA', 'date' = '2017-10-02');
USE test_db2;
CREATE TABLE test_tbl (col1 TINYINT, col2 SMALLINT, col3 INT, col4 BIGINT, col5 BOOLEAN, col6 FLOAT, col7 DOUBLE, col8 STRING, col9 TIMESTAMP);
SHOW TABLES;
SHOW TABLES LIKE 'test*';
DROP TABLE test_tbl;
DROP DATABASE test_db2;