DROP DATABASE IF EXISTS db4func CASCADE;
CREATE DATABASE db4func;
USE db4func;
ADD JAR /opt/meituan/qa_test/sentry-test/src/test/resources/hive-data/hive_qa_udf.jar;
LIST JARS;
CREATE FUNCTION qa_lower AS 'com.example.hive.udf.LowerCase';
CREATE TABLE teacher (name STRING);
INSERT INTO teacher VALUES ('TEACHER QA');
SELECT qa_lower(name) as name FROM teacher;
DROP TABLE teacher;
DELETE JAR /opt/meituan/qa_test/testfile/hive_qa_udf.jar;
LIST JARS;
DROP DATABASE db4func;