--DROP VIEW db4tbl.view2create;
--DROP TABLE db4tbl.tbl2create;
--DROP VIEW db4tbl.view4show;
--DROP TABLE db4tbl.tbl4show;

SHOW TABLES;
CREATE TABLE db4tbl.tbl2create (col1 TINYINT, col2 SMALLINT);
CREATE VIEW db4tbl.view2create AS SELECT col1, col2 FROM db4tbl.tbl4show;
SHOW TABLES;
ALTER TABLE db4tbl.tbl4show SET TBLPROPERTIES ('qa comments' = 'test add table properties');
ALTER TABLE db4tbl.tbl2create SET TBLPROPERTIES ('qa comments' = 'test add table properties');
ALTER VIEW db4tbl.view2create SET TBLPROPERTIES ('qa comments' = 'test add table properties');
ALTER VIEW db4tbl.view4show SET TBLPROPERTIES ('qa comments' = 'test add table properties');
USE db4tbl;
SHOW TABLES LIKE '*2create';
DROP VIEW db4tbl.view4show;
DROP TABLE db4tbl.tbl4show;
DESCRIBE EXTENDED db4tbl.view2create;
SHOW CREATE TABLE db4tbl.view2create;
SHOW TABLES;
DROP VIEW db4tbl.view2create;
DROP TABLE db4tbl.tbl2create;
