DROP TABLE db4load.collecttest;
DROP DATABASE db4load;
DROP DATABASE db4query CASCADE;
DROP TABLE db4overwrite.table001;
DROP TABLE db4overwrite.table002;
DROP DATABASE db4overwrite;
DROP TABLE db4func.teacher;
DROP DATABASE db4func;
DROP TABLE db4addfile.whoyouare;
DROP DATABASE db4addfile;
DROP TABLE db4alter.test_serde;
DROP TABLE db4alter.test_serde_partition;
DROP DATABASE db4alter;
DROP DATABASE db4alter2 CASCADE;
DROP TABLE test_db.staged_employees;
DROP TABLE test_db.employees;
DROP TABLE test_db.employees02;
DROP TABLE test_db.staged_employees02;
DROP TABLE test_db.log_messages02;
DROP TABLE test_db.test_msck;
DROP TABLE test_db.employees_props;
DROP DATABASE test_db CASCADE;