CREATE TABLE test_db.whoyouare(who string);
SET FILEPATH=/opt/meituan/qa_test/sentry-test/src/test/resources/hive-data;
LOAD DATA LOCAL INPATH '${hiveconf:FILEPATH}/who.txt' OVERWRITE INTO TABLE test_db.whoyouare;
SET hive.cli.print.header=true;
SELECT * FROM test_db.whoyouare;
ADD FILE '${hiveconf:FILEPATH}/test_who.sh';
LIST FILES;
SET hive.cli.print.header=true;
SELECT TRANSFORM (who) USING 'sh test_who.sh' AS (who) FROM test_db.whoyouare;
DELETE FILE '${hiveconf:FILEPATH}/test_who.sh';
LIST FILE;
DROP TABLE test_db.whoyouare;
